---
title: "strings and factors"
author: "Wenjie Wu"
output: github_document
---

```{r setup, include=FALSE}
library(rvest)
library(stringr)
library(forcats)
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
string_vec = c("my", "name", "is", "xx")

str_detect(string_vec, "name")

str_replace(string_vec, "xx", "XX")

str_replace(string_vec, "x", "X" )
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")

str_detect(string_vec, "^i think") # Beginning of the line
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "pumpkin")

str_detect(string_vec, "Pumpkin")

str_detect(string_vec, "[Pp]umpkin") # Two options

```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-zA-Z]") # Find all numbers followed by letters


```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11") # . matches everything
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[") # \\ + what are really looking for --> [
```

```{r}
sex_vec = factor(c("male", "male", "female", "female"))

as.numeric(sex_vec)
```

```{r}
sex_vec = fct_relevel(sex_vec, "male")

as.numeric(sex_vec)
```

NSDUH

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

```{r}
marj_use_df = 
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1) |>
  select(-contains("P Value")) |>
  pivot_longer(
    cols = -State,
    names_to = "age_year",
    values_to = "percent"
  ) |>
  separate(age_year, int = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_remove(percent, "[a-c]$"),
    percent = as.numeric(percent)
  )
```

```{r}
marj_use_df |>
  filter(age == "12-17") |>
  mutate(
    State = fct_reorder(State, percent)
  ) |>
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

